[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\adchurch\archive\vs_cds\waveform processing addon'

[projects.cd]
path = 'Source\Waveform-Processing-Custom-Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[package]
type = 'nipkg'
name = 'waveform-processing-custom-device-{veristand_version}'
dev_xml_path = 'Source\Custom Device Waveform Processing Custom Device.xml'
install_destination = 'documents\National Instruments\NI VeriStand {version}\Custom Devices'
