[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\adchurch\archive\vs_cds\waveform processing addon'

[projects.cd]
path = 'Source\Waveform-Processing-Custom-Device.lvproj'

[projects.api]
path = 'Source\Waveform-Processing-Custom-Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'
