[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\adchurch\archive\vs_cds\waveform processing addon'

[projects.cd]
path = 'Source\Waveform-Processing-Custom-Device.lvproj'

[projects.api]
path = 'Source\Waveform-Processing-Custom-Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[package]
type = 'nipkg'
name = 'waveform-processing-custom-device'
version = '1.0.0.0'
maintainer = 'Andy Church (andy.church@ni.com)'
description = 'This is a package for the Waveform Processing Custom Device.'
homepage = 'www.ni.com'
display_name = 'Waveform Processing Custom Device'
eula_dependency = 'eula-pkg'
dependencies = ['pkg1', 'pkg2']
